/* Generated By:JavaCC: Do not edit this line. FelixConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FelixConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int SET = 6;
  /** RegularExpression Id. */
  int TO = 7;
  /** RegularExpression Id. */
  int WRITE = 8;
  /** RegularExpression Id. */
  int READ = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int THEN = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int ENDIF = 13;
  /** RegularExpression Id. */
  int NEW = 14;
  /** RegularExpression Id. */
  int MATRIX = 15;
  /** RegularExpression Id. */
  int ARRAY = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int NOT = 19;
  /** RegularExpression Id. */
  int TRUE = 20;
  /** RegularExpression Id. */
  int FALSE = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int DO = 23;
  /** RegularExpression Id. */
  int ENDWHILE = 24;
  /** RegularExpression Id. */
  int FOR = 25;
  /** RegularExpression Id. */
  int ENDFOR = 26;
  /** RegularExpression Id. */
  int SWITCH = 27;
  /** RegularExpression Id. */
  int CASE = 28;
  /** RegularExpression Id. */
  int DEFAULT_CASE = 29;
  /** RegularExpression Id. */
  int ENDSWITCH = 30;
  /** RegularExpression Id. */
  int SEMICOLON = 31;
  /** RegularExpression Id. */
  int PLUS = 32;
  /** RegularExpression Id. */
  int MINUS = 33;
  /** RegularExpression Id. */
  int TIMES = 34;
  /** RegularExpression Id. */
  int DIV = 35;
  /** RegularExpression Id. */
  int LPAREN = 36;
  /** RegularExpression Id. */
  int RPAREN = 37;
  /** RegularExpression Id. */
  int LBRACKET = 38;
  /** RegularExpression Id. */
  int RBRACKET = 39;
  /** RegularExpression Id. */
  int EQ = 40;
  /** RegularExpression Id. */
  int NEQ = 41;
  /** RegularExpression Id. */
  int GE = 42;
  /** RegularExpression Id. */
  int LE = 43;
  /** RegularExpression Id. */
  int GT = 44;
  /** RegularExpression Id. */
  int LT = 45;
  /** RegularExpression Id. */
  int ASSIGN_OP = 46;
  /** RegularExpression Id. */
  int COMMA = 47;
  /** RegularExpression Id. */
  int REAL_LIT = 48;
  /** RegularExpression Id. */
  int INTEGER_LIT = 49;
  /** RegularExpression Id. */
  int IDENTIFIER = 50;
  /** RegularExpression Id. */
  int STRING_LITERAL = 51;
  /** RegularExpression Id. */
  int ERROR = 52;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "\"SET\"",
    "\"TO\"",
    "\"WRITE\"",
    "\"READ\"",
    "\"IF\"",
    "\"THEN\"",
    "\"ELSE\"",
    "\"ENDIF\"",
    "\"NEW\"",
    "\"MATRIX\"",
    "\"ARRAY\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"WHILE\"",
    "\"DO\"",
    "\"ENDWHILE\"",
    "\"FOR\"",
    "\"ENDFOR\"",
    "\"SWITCH\"",
    "\"CASE\"",
    "\"DEFAULT_CASE\"",
    "\"ENDSWITCH\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"==\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\",\"",
    "<REAL_LIT>",
    "<INTEGER_LIT>",
    "<IDENTIFIER>",
    "<STRING_LITERAL>",
    "<ERROR>",
  };

}
