/* Felix.java */
/* Generated By:JavaCC: Do not edit this line. Felix.java */
import java.util.*;

// ============================================================
// AST NODES
// ============================================================
abstract class ExprNode { String type; }

class LiteralNode extends ExprNode {
    String value;
    public LiteralNode(String value, String type) { this.value = value; this.type = type; }
}

class VariableNode extends ExprNode {
    String name;
    public VariableNode(String name) { this.name = name; this.type = "PENDING_LOOKUP"; }
}

class BinaryOpNode extends ExprNode {
    ExprNode left, right; String operator;
    public BinaryOpNode(String operator, ExprNode left, ExprNode right) {
        this.operator = operator;
        this.left = left; this.right = right;
    }
}

class UnaryOpNode extends ExprNode {
    ExprNode operand; String operator;
    public UnaryOpNode(String operator, ExprNode operand) {
        this.operator = operator; this.operand = operand;
    }
}

class MatrixAccessNode extends ExprNode {
    String name; ExprNode row, col;
    public MatrixAccessNode(String name, ExprNode row, ExprNode col) {
        this.name = name;
        this.row = row; this.col = col; this.type = "PENDING_LOOKUP";
    }
}

class ArrayAccessNode extends ExprNode {
    String name; ExprNode index;
    public ArrayAccessNode(String name, ExprNode index) {
        this.name = name;
        this.index = index; this.type = "PENDING_LOOKUP";
    }
}

// ============================================================
// INTERMEDIATE CODE — QUADRUPLES
// ============================================================
class IntermediateInstruction {
    String operator, arg1, arg2, result;
    public IntermediateInstruction(String op, String a1, String a2, String res) {
        this.operator = op;
        this.arg1 = a1; this.arg2 = a2; this.result = res;
    }
}

// ============================================================
// BLOQUES BÁSICOS + UTILIDADES
// ============================================================
class BasicBlock {
    int id;
    List<IntermediateInstruction> instructions = new ArrayList<IntermediateInstruction>();
    public BasicBlock(int id) { this.id = id; }
}

class OptimizerUtils {
    public static List<BasicBlock> buildBlocks(List<IntermediateInstruction> code) {
        List<BasicBlock> blocks = new ArrayList<BasicBlock>();
        BasicBlock current = new BasicBlock(0);
        blocks.add(current);
        for (IntermediateInstruction ins : code) {
            if (ins.operator.equals("LABEL")) {
                current = new BasicBlock(blocks.size());
                blocks.add(current);
                current.instructions.add(ins);
            } else {
                current.instructions.add(ins);
                if (ins.operator.equals("GOTO") || ins.operator.equals("IFT")) {
                    current = new BasicBlock(blocks.size());
                    blocks.add(current);
                }
            }
        }
        return blocks;
    }

    public static List<IntermediateInstruction> flatten(List<BasicBlock> blocks) {
        List<IntermediateInstruction> code = new ArrayList<IntermediateInstruction>();
        for (BasicBlock b : blocks) code.addAll(b.instructions);
        return code;
    }

    public static String applyMap(String operand, Map<String, String> map) {
        if (operand == null) return null;
        String resolved = operand;
        Set<String> visited = new HashSet<String>();
        while (map.containsKey(resolved) && !visited.contains(resolved)) {
            visited.add(resolved);
            resolved = map.get(resolved);
        }
        return resolved;
    }

    public static boolean isTemp(String s) {
        return s != null && (s.matches("t\\d+") || s.startsWith("t_"));
    }

    public static boolean isLiteral(String s) {
        if (s == null) return false;
        return s.matches("-?\\d+(\\.\\d+)?") || s.startsWith("\"");
    }
}

interface Optimizer {
    List<IntermediateInstruction> optimize(List<IntermediateInstruction> code);
}

// ============================================================
// 0. PEEPHOLE OPTIMIZER (Colapso de Temporales)
// ============================================================
class PeepholeOptimizer implements Optimizer {
    public List<IntermediateInstruction> optimize(List<IntermediateInstruction> code) {
        List<IntermediateInstruction> result = new ArrayList<IntermediateInstruction>();
        for (int i = 0; i < code.size(); i++) {
            IntermediateInstruction curr = code.get(i);
            if (i < code.size() - 1) {
                IntermediateInstruction next = code.get(i + 1);
                if (curr.result != null && OptimizerUtils.isTemp(curr.result) &&
                    next.operator.equals("=") && next.arg1 != null &&
                    next.arg1.equals(curr.result) && next.arg2 == null) {
                    curr.result = next.result;
                    result.add(curr);
                    i++;
                    continue;
                }
            }
            result.add(curr);
        }
        return result;
    }
}

// ============================================================
// 1. ELIMINACIÓN DE SUBEXPRESIONES COMUNES (CSE)
// ============================================================
class CommonSubexpressionElimination implements Optimizer {
    public List<IntermediateInstruction> optimize(List<IntermediateInstruction> code) {
        List<BasicBlock> blocks = OptimizerUtils.buildBlocks(code);
        for (BasicBlock block : blocks) {
            Map<String, String> exprTable    = new HashMap<String, String>();
            Map<String, String> replacements = new HashMap<String, String>();
            List<IntermediateInstruction> clean = new ArrayList<IntermediateInstruction>();
            for (IntermediateInstruction ins : block.instructions) {
                ins.arg1 = OptimizerUtils.applyMap(ins.arg1, replacements);
                ins.arg2 = OptimizerUtils.applyMap(ins.arg2, replacements);

                boolean isRedundant = false;

                if (ins.arg1 != null && ins.arg2 != null
                        && !ins.operator.equals("=")
                        && !ins.operator.startsWith("IF")
                        && !ins.operator.equals("GOTO")
                        && !ins.operator.equals("LABEL")
                        && !ins.operator.equals("WRITE")
                        && !ins.operator.equals("READ")
                        && !ins.operator.equals("NEWMAT")
                        && !ins.operator.equals("MATGET")) {

                    String key = ins.operator + "|" + ins.arg1 + "|" + ins.arg2;
                    if (exprTable.containsKey(key)) {
                        replacements.put(ins.result, exprTable.get(key));
                        isRedundant = true;
                    } else {
                        exprTable.put(key, ins.result);
                    }
                }

                if (ins.result != null && !isRedundant) {
                    List<String> toRemove = new ArrayList<String>();
                    for (String key : exprTable.keySet()) {
                        String[] parts = key.split("\\|");
                        if (parts.length == 3 && (parts[1].equals(ins.result) || parts[2].equals(ins.result))) {
                            toRemove.add(key);
                        }
                    }
                    for (String k : toRemove) exprTable.remove(k);
                }

                if (!isRedundant) clean.add(ins);
            }
            block.instructions = clean;
        }
        return OptimizerUtils.flatten(blocks);
    }
}

// ============================================================
// 2. PROPAGACIÓN DE COPIAS (global, dos pasadas)
// ============================================================
class CopyPropagation implements Optimizer {
    public List<IntermediateInstruction> optimize(List<IntermediateInstruction> code) {
        List<BasicBlock> blocks = OptimizerUtils.buildBlocks(code);
        for (BasicBlock block : blocks) {
            Map<String, String> copyMap = new LinkedHashMap<String, String>();
            for (IntermediateInstruction ins : block.instructions) {
                ins.arg1 = OptimizerUtils.applyMap(ins.arg1, copyMap);
                ins.arg2 = OptimizerUtils.applyMap(ins.arg2, copyMap);

                if (ins.operator.equals("=") && ins.arg2 == null && ins.arg1 != null && ins.result != null) {
                    if (OptimizerUtils.isTemp(ins.arg1) && !OptimizerUtils.isTemp(ins.result)) {
                        copyMap.put(ins.arg1, ins.result);
                    } else {
                        copyMap.put(ins.result, ins.arg1);
                    }
                } else if (ins.result != null) {
                    List<String> toRemove = new ArrayList<String>();
                    for (Map.Entry<String, String> entry : copyMap.entrySet()) {
                        if (entry.getKey().equals(ins.result) || entry.getValue().equals(ins.result)) {
                            toRemove.add(entry.getKey());
                        }
                    }
                    for (String k : toRemove) copyMap.remove(k);
                }
            }
        }
        return OptimizerUtils.flatten(blocks);
    }
}

// ============================================================
// 3. REDUCCIÓN DE FRECUENCIA EN CICLOS (Loop Invariant Code Motion)
// ============================================================
class LoopInvariantCodeMotion implements Optimizer {
    public List<IntermediateInstruction> optimize(List<IntermediateInstruction> code) {
        List<IntermediateInstruction> result = new ArrayList<IntermediateInstruction>(code);
        boolean changed = true;

        while (changed) {
            changed = false;
            Map<String, Integer> labelPos = new LinkedHashMap<String, Integer>();
            for (int i = 0; i < result.size(); i++) {
                IntermediateInstruction ins = result.get(i);
                if (ins.operator.equals("LABEL")) {
                    labelPos.put(ins.result, i);
                }
            }

            for (int gotoIdx = 0; gotoIdx < result.size(); gotoIdx++) {
                IntermediateInstruction gotoIns = result.get(gotoIdx);
                if (!gotoIns.operator.equals("GOTO")) continue;
                if (!labelPos.containsKey(gotoIns.result)) continue;

                int labelIdx = labelPos.get(gotoIns.result);
                if (labelIdx >= gotoIdx) continue;

                Set<String> modified = new HashSet<String>();
                for (int i = labelIdx; i <= gotoIdx; i++) {
                    IntermediateInstruction ins = result.get(i);
                    if (ins.result != null && !ins.operator.equals("LABEL") && !ins.operator.equals("IFT") && !ins.operator.equals("GOTO")) {
                        modified.add(ins.result);
                    }
                }

                List<IntermediateInstruction> toHoist  = new ArrayList<IntermediateInstruction>();
                List<Integer>                hoistIdxs = new ArrayList<Integer>();
                for (int i = labelIdx + 1; i < gotoIdx; i++) {
                    IntermediateInstruction ins = result.get(i);
                    if (ins.operator.equals("LABEL") || ins.operator.equals("GOTO")
                            || ins.operator.equals("IFT")  || ins.operator.equals("WRITE")
                            || ins.operator.equals("READ")  || ins.operator.equals("NEWMAT")) continue;
                    if (ins.result == null) continue;

                    boolean arg1Safe = ins.arg1 == null || OptimizerUtils.isLiteral(ins.arg1) || !modified.contains(ins.arg1);
                    boolean arg2Safe = ins.arg2 == null || OptimizerUtils.isLiteral(ins.arg2) || !modified.contains(ins.arg2);

                    int defCount = 0;
                    for (int j = labelIdx; j <= gotoIdx; j++) {
                        if (result.get(j).result != null && result.get(j).result.equals(ins.result)) defCount++;
                    }

                    if (arg1Safe && arg2Safe && defCount == 1) {
                        toHoist.add(ins);
                        hoistIdxs.add(i);
                        changed = true;
                    }
                }

                if (!toHoist.isEmpty()) {
                    for (int i = hoistIdxs.size() - 1; i >= 0; i--) {
                        result.remove((int) hoistIdxs.get(i));
                    }
                    int newLabelIdx = -1;
                    for (int i = 0; i < result.size(); i++) {
                        if (result.get(i).operator.equals("LABEL") && result.get(i).result != null && result.get(i).result.equals(gotoIns.result)) {
                            newLabelIdx = i;
                            break;
                        }
                    }
                    if (newLabelIdx >= 0) result.addAll(newLabelIdx, toHoist);
                    break;
                }
            }
        }
        return result;
    }
}

// ============================================================
// 4. ELIMINACIÓN DE CÓDIGO MUERTO (DCE)
// ============================================================
class DeadCodeElimination implements Optimizer {
    public List<IntermediateInstruction> optimize(List<IntermediateInstruction> code) {
        boolean changed = true;
        List<IntermediateInstruction> current = new ArrayList<IntermediateInstruction>(code);

        while (changed) {
            changed = false;
            Set<String> used = new HashSet<String>();
            for (IntermediateInstruction ins : current) {
                if (ins.arg1 != null) used.add(ins.arg1);
                if (ins.arg2 != null) used.add(ins.arg2);
                if (ins.operator.equals("IFT") && ins.result != null) used.add(ins.result);
            }

            List<IntermediateInstruction> clean = new ArrayList<IntermediateInstruction>();
            for (IntermediateInstruction ins : current) {
                boolean isDead = false;
                if (ins.result != null && !used.contains(ins.result)) {
                    if (!ins.operator.equals("READ") &&
                        !ins.operator.equals("NEWMAT") &&
                        !ins.operator.equals("WRITE") &&
                        !ins.operator.equals("LABEL") &&
                        !ins.operator.equals("GOTO")) {
                        isDead = true;
                    }
                }
                if (isDead) {
                    changed = true;
                } else {
                    clean.add(ins);
                }
            }
            current = clean;
        }
        return current;
    }
}

// ============================================================
// PIPELINE DE OPTIMIZACIÓN
// ============================================================
class OptimizationPipeline {
    private List<Optimizer> optimizers = new ArrayList<Optimizer>();
    public void addOptimizer(Optimizer opt) { optimizers.add(opt); }

    public List<IntermediateInstruction> run(List<IntermediateInstruction> code) {
        List<IntermediateInstruction> result = new ArrayList<IntermediateInstruction>(code);
        int prevSize = -1;
        while (result.size() != prevSize) {
            prevSize = result.size();
            for (Optimizer opt : optimizers) {
                result = opt.optimize(result);
            }
        }
        return result;
    }
}

// ============================================================
// SYMBOL TABLE
// ============================================================
class Symbol {
    String name, type; int dim1, dim2, address; String scope;
    public Symbol(String name, String type, int address, String scope) {
        this.name = name;
        this.type = type; this.address = address; this.scope = scope;
    }
    public Symbol(String name, int d1, int d2, int addr, String scope) {
        this.name = name;
        this.type = "MATRIX"; this.dim1 = d1; this.dim2 = d2;
        this.address = addr; this.scope = scope;
    }
    public Symbol(String name, int size, int addr, String scope) {
        this.name = name;
        this.type = "ARRAY"; this.dim1 = size;
        this.address = addr; this.scope = scope;
    }
}

class MemoryManager {
    private int nextFreeAddress = 0;
    public int allocate(String type) { int a = nextFreeAddress; nextFreeAddress += 4; return a; }
    public int allocate(int totalSize) { int a = nextFreeAddress; nextFreeAddress += totalSize; return a; }
}

class SymbolTable {
    private Map<String, Symbol> table = new HashMap<String, Symbol>();
    private MemoryManager memoryManager;
    private String currentScope = "GLOBAL";

    public SymbolTable(MemoryManager mm) { this.memoryManager = mm; }
    public void setScope(String scope) { this.currentScope = scope; }
    public String getScope() { return currentScope; }

    public boolean addVariable(String name, String type) {
        String key = (name + "@" + currentScope).toUpperCase();
        if (table.containsKey(key)) return false;
        int addr = memoryManager.allocate(type);
        table.put(key, new Symbol(name, type, addr, currentScope));
        return true;
    }

    public boolean addMatrix(String name, int d1, int d2) {
        String key = (name + "@" + currentScope).toUpperCase();
        if (table.containsKey(key)) return false;
        int addr = memoryManager.allocate(d1 * d2 * 4);
        table.put(key, new Symbol(name, d1, d2, addr, currentScope));
        return true;
    }

    public boolean addArray(String name, int size) {
        String key = (name + "@" + currentScope).toUpperCase();
        if (table.containsKey(key)) return false;
        int addr = memoryManager.allocate(size * 4);
        table.put(key, new Symbol(name, size, addr, currentScope));
        return true;
    }

    public Symbol lookup(String name) {
        String key = (name + "@" + currentScope).toUpperCase();
        if (table.containsKey(key)) return table.get(key);
        key = (name + "@GLOBAL").toUpperCase();
        return table.get(key);
    }

    public boolean isDeclared(String name) { return lookup(name) != null; }
}

// ============================================================
// SEMANTIC ERROR
// ============================================================
class SemanticError {
    int line, column; String description, expected, suggestion;
    public SemanticError(int line, int column, String description, String expected, String suggestion) {
        this.line = line;
        this.column = column;
        this.description = description; this.expected = expected; this.suggestion = suggestion;
    }
    public String toString() {
        return "\n==================================================\n" +
               "ERROR SEMANTICO\n\n" +
               "Linea: " + line + "\n" +
               "Columna: " + column + "\n\n" +
               "Descripcion: " + description + "\n\n" +
               "Se esperaba: " + expected + "\n\n" +
               "Sugerencia: " + suggestion + "\n" +
               "==================================================";
    }
}

// ============================================================
// CODE GENERATOR WALKER
// ============================================================
class CodeGeneratorWalker {
    private SymbolTable symbolTable;
    private List<SemanticError> errors;
    private List<IntermediateInstruction> code;
    private int tempCounter = 0;

    public CodeGeneratorWalker(SymbolTable st, List<SemanticError> errors, List<IntermediateInstruction> code) {
        this.symbolTable = st;
        this.errors = errors; this.code = code;
    }

    private String newTemp() { return "t" + (++tempCounter); }
    public ExpressionResult walk(ExprNode node) { return walk(node, 0, 0); }

    public ExpressionResult walk(ExprNode node, int line, int col) {
        if (node instanceof LiteralNode) {
            LiteralNode n = (LiteralNode) node;
            return new ExpressionResult(n.value, n.type);
        }
        if (node instanceof VariableNode) {
            VariableNode n = (VariableNode) node;
            Symbol s = symbolTable.lookup(n.name);
            if (s == null) {
                errors.add(new SemanticError(line, col,
                    "Variable '" + n.name + "' no ha sido declarada.",
                    "Una variable previamente declarada con SET o READ.",
                    "Declare la variable antes de usarla: SET " + n.name + " TO <valor>;"));
                return new ExpressionResult(n.name, "UNKNOWN");
            }
            return new ExpressionResult(n.name, s.type);
        }
        if (node instanceof MatrixAccessNode) {
            MatrixAccessNode n = (MatrixAccessNode) node;
            Symbol s = symbolTable.lookup(n.name);
            if (s == null) {
                errors.add(new SemanticError(line, col,
                    "Matriz '" + n.name + "' no ha sido declarada.",
                    "Una matriz declarada con NEW MATRIX.",
                    "Declare la matriz: NEW MATRIX " + n.name + "[dim1][dim2];"));
                return new ExpressionResult(n.name, "UNKNOWN");
            }
            if (!s.type.equals("MATRIX")) {
                errors.add(new SemanticError(line, col,
                    "'" + n.name + "' no es una matriz.",
                    "Una variable de tipo MATRIX.",
                    "Use una variable declarada como matriz."));
                return new ExpressionResult(n.name, "UNKNOWN");
            }
            ExpressionResult r = walk(n.row, line, col);
            ExpressionResult c = walk(n.col, line, col);
            String temp = newTemp();
            code.add(new IntermediateInstruction("MATGET", n.name, r.operand + "," + c.operand, temp));
            return new ExpressionResult(temp, "REAL");
        }
        if (node instanceof ArrayAccessNode) {
            ArrayAccessNode n = (ArrayAccessNode) node;
            Symbol s = symbolTable.lookup(n.name);
            if (s == null) {
                errors.add(new SemanticError(line, col,
                    "Arreglo '" + n.name + "' no ha sido declarado.",
                    "Un arreglo declarado con NEW ARRAY.",
                    "Declare el arreglo: NEW ARRAY " + n.name + "[tama\u00f1o];"));
                return new ExpressionResult(n.name, "UNKNOWN");
            }
            ExpressionResult idx = walk(n.index, line, col);
            String temp = newTemp();
            code.add(new IntermediateInstruction("ARRGET", n.name, idx.operand, temp));
            return new ExpressionResult(temp, "REAL");
        }
        if (node instanceof UnaryOpNode) {
            UnaryOpNode n = (UnaryOpNode) node;
            ExpressionResult operand = walk(n.operand, line, col);
            if (n.operator.equals("NOT")) {
                if (!operand.type.equals("BOOLEAN") && !operand.type.equals("UNKNOWN")) {
                    errors.add(new SemanticError(line, col,
                        "Operador NOT aplicado a tipo '" + operand.type + "'.",
                        "Tipo BOOLEAN.",
                        "Use NOT solo con expresiones booleanas."));
                }
                String temp = newTemp();
                code.add(new IntermediateInstruction("NOT", operand.operand, null, temp));
                return new ExpressionResult(temp, "BOOLEAN");
            }
            if (n.operator.equals("NEG")) {
                if (!isNumeric(operand.type) && !operand.type.equals("UNKNOWN")) {
                    errors.add(new SemanticError(line, col,
                        "Negacion unaria aplicada a tipo '" + operand.type + "'.",
                        "Tipo INTEGER o REAL.",
                        "Use el operador '-' solo con valores numericos."));
                }
                String temp = newTemp();
                code.add(new IntermediateInstruction("NEG", operand.operand, null, temp));
                return new ExpressionResult(temp, operand.type);
            }
            return operand;
        }
        if (node instanceof BinaryOpNode) {
            BinaryOpNode n = (BinaryOpNode) node;
            ExpressionResult left  = walk(n.left,  line, col);
            ExpressionResult right = walk(n.right, line, col);
            String op = n.operator;
            String resultType = "UNKNOWN";

            if (op.equals("+") || op.equals("-") || op.equals("*") || op.equals("/")) {
                if (!isNumeric(left.type) && !left.type.equals("UNKNOWN")) {
                    errors.add(new SemanticError(line, col,
                        "Operacion aritmetica '" + op + "' con tipo no numerico '" + left.type + "'.",
                        "Tipo INTEGER o REAL.",
                        "Use solo valores numericos en operaciones aritmeticas."));
                } else if (!isNumeric(right.type) && !right.type.equals("UNKNOWN")) {
                    errors.add(new SemanticError(line, col,
                        "Operacion aritmetica '" + op + "' con tipo no numerico '" + right.type + "'.",
                        "Tipo INTEGER o REAL.",
                        "Use solo valores numericos en operaciones aritmeticas."));
                }

                if (!left.type.equals("UNKNOWN") && !right.type.equals("UNKNOWN") && !left.type.equals(right.type)) {
                    errors.add(new SemanticError(line, col,
                        "Operacion aritmetica '" + op + "' entre tipos incompatibles '" + left.type + "' y '" + right.type + "'.",
                        "Ambos operandos del mismo tipo numerico.",
                        "Realice la operacion entre operandos del mismo tipo."));
                }

                if (isNumeric(left.type) && isNumeric(right.type)) {
                    resultType = left.type;
                } else if (!left.type.equals("UNKNOWN")) {
                    resultType = left.type;
                } else if (!right.type.equals("UNKNOWN")) {
                    resultType = right.type;
                } else {
                    resultType = "UNKNOWN";
                }
            } else if (op.equalsIgnoreCase("AND") || op.equalsIgnoreCase("OR")) {
                if (!left.type.equals("BOOLEAN") && !left.type.equals("UNKNOWN")) {
                    errors.add(new SemanticError(line, col,
                        "Operacion logica '" + op + "' con tipo no booleano '" + left.type + "'.",
                        "Tipo BOOLEAN.",
                        "Use solo valores booleanos con AND / OR."));
                }
                if (!right.type.equals("BOOLEAN") && !right.type.equals("UNKNOWN")) {
                    errors.add(new SemanticError(line, col,
                        "Operacion logica '" + op + "' con tipo no booleano '" + right.type + "'.",
                        "Tipo BOOLEAN.",
                        "Use solo valores booleanos con AND / OR."));
                }
                resultType = "BOOLEAN";
            } else if (op.equals("==") || op.equals("!=")) {
                if (!left.type.equals("UNKNOWN") && !right.type.equals("UNKNOWN") &&
                    !left.type.equals(right.type)) {
                    errors.add(new SemanticError(line, col,
                        "Comparacion '" + op + "' entre tipos incompatibles '" + left.type + "' y '" + right.type + "'.",
                        "Ambos operandos del mismo tipo.",
                        "Compare valores del mismo tipo."));
                }
                resultType = "BOOLEAN";
            } else if (op.equals(">") || op.equals(">=") || op.equals("<") || op.equals("<=")) {
                if (!isNumeric(left.type) && !left.type.equals("UNKNOWN")) {
                    errors.add(new SemanticError(line, col,
                        "Comparacion '" + op + "' con tipo no numerico '" + left.type + "'.",
                        "Tipo INTEGER o REAL.",
                        "Use solo numeros en comparaciones de orden."));
                }
                if (!isNumeric(right.type) && !right.type.equals("UNKNOWN")) {
                    errors.add(new SemanticError(line, col,
                        "Comparacion '" + op + "' con tipo no numerico '" + right.type + "'.",
                        "Tipo INTEGER o REAL.",
                        "Use solo numeros en comparaciones de orden."));
                }
                if (!left.type.equals("UNKNOWN") && !right.type.equals("UNKNOWN") && !left.type.equals(right.type)) {
                    errors.add(new SemanticError(line, col,
                        "Comparacion '" + op + "' entre tipos incompatibles '" + left.type + "' y '" + right.type + "'.",
                        "Ambos operandos del mismo tipo.",
                        "Compare valores del mismo tipo."));
                }
                resultType = "BOOLEAN";
            }

            String temp = newTemp();
            code.add(new IntermediateInstruction(op, left.operand, right.operand, temp));
            return new ExpressionResult(temp, resultType);
        }
        return new ExpressionResult("error", "UNKNOWN");
    }

    private boolean isNumeric(String type) {
        return type.equals("INTEGER") || type.equals("REAL");
    }
}

class ExpressionResult {
    String operand, type;
    public ExpressionResult(String operand, String type) { this.operand = operand; this.type = type; }
}

// ============================================================
// MAIN PARSER CLASS
// ============================================================
public class Felix implements FelixConstants {
    private MemoryManager memoryManager = new MemoryManager();
    private SymbolTable symbolTable = new SymbolTable(memoryManager);
    private List<SemanticError> semanticErrors = new ArrayList<SemanticError>();
    public List<String> lexicErrors = new ArrayList<String>();
    public List<String> syntaxErrors = new ArrayList<String>();
    private List<IntermediateInstruction> intermediateCode = new ArrayList<IntermediateInstruction>();
    private Stack<ExprNode> semanticStack = new Stack<ExprNode>();
    private int labelCounter = 0;
    private String newLabel() { return "L" + (++labelCounter); }

    private CodeGeneratorWalker walkerInstance = null;
    private CodeGeneratorWalker walker() {
        if (walkerInstance == null) {
            walkerInstance = new CodeGeneratorWalker(symbolTable, semanticErrors, intermediateCode);
        }
        return walkerInstance;
    }

    private void initTokenManager() {
        token_source.parserRef = this;
    }

    public static void main(String[] args) {
        java.io.InputStream inputStream = System.in;
        String sourceFileName = "entrada";
        boolean readFromStdin = (args.length == 0);

        boolean noExec = false;
        if (args.length > 0) {
            sourceFileName = args[0];
            if (args.length > 1 && args[1].equalsIgnoreCase("-noexec")) {
                noExec = true;
            }
            try {
                inputStream = new java.io.FileInputStream(args[0]);
            } catch (java.io.FileNotFoundException ex) {
                System.out.println("ERROR: No se encontr\u00f3 el archivo '" + args[0] + "'.");
                System.exit(1);
            }
        } else {
            // Leer todo stdin en un buffer para que el parser no consuma System.in
            // El usuario debe presionar Ctrl+D (Unix/Mac), Ctrl+Z (Windows) o escribir EOF para terminar
            System.out.println("Escribe tu c\u00f3digo Felix. Presiona Ctrl+D (Mac/Linux), Ctrl+Z (Windows) o escribe EOF y presiona Enter para compilar:");
            System.out.println("--------------------------------------------------");
            System.out.flush();
            try {
                java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
                java.io.BufferedReader reader = new java.io.BufferedReader(new java.io.InputStreamReader(System.in, "UTF-8"));
                String line;
                while ((line = reader.readLine()) != null) {
                    if (line.trim().equalsIgnoreCase("EOF")) {
                        break;
                    }
                    baos.write(line.getBytes("UTF-8"));
                    baos.write('\n');
                }
                inputStream = new java.io.ByteArrayInputStream(baos.toByteArray());
            } catch (Exception ex) {
                System.out.println("ERROR: No se pudo leer la entrada est\u00e1ndar.");
                System.exit(1);
            }
        }

        String baseName = sourceFileName;
        int dotIndex = sourceFileName.lastIndexOf('.');
        if (dotIndex > 0) baseName = sourceFileName.substring(0, dotIndex);
        String outputFileName = baseName + "_cuadruples.txt";
        java.time.LocalDateTime now = java.time.LocalDateTime.now();
        java.time.format.DateTimeFormatter fmt = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        String timestamp = now.format(fmt);

        Felix parser = new Felix(inputStream);
        try {
            parser.Start();
        } catch (ParseException e) {
            Token errTok = e.currentToken != null && e.currentToken.next != null ? e.currentToken.next : e.currentToken;
            if (errTok == null || errTok.kind != ERROR) {
                int eLine = errTok != null ? errTok.beginLine : 0;
                int eCol  = errTok != null ? errTok.beginColumn : 0;
                parser.syntaxErrors.add("L\u00ednea " + eLine + ", Columna " + eCol + ": " + traducirExpectedTokens(e));
            }
        } catch (TokenMgrError e) {
            parser.syntaxErrors.add("Car\u00e1cter no reconocido (error l\u00e9xico fatal).");
        }

        boolean hayErrores = !parser.syntaxErrors.isEmpty() || !parser.semanticErrors.isEmpty() || !parser.lexicErrors.isEmpty();

        if (!parser.lexicErrors.isEmpty()) {
            System.out.println("\n==================================================");
            System.out.println("ERRORES L\u00c9XICOS DETECTADOS (" + parser.lexicErrors.size() + "):");
            System.out.println("==================================================");
            for (String le : parser.lexicErrors) {
                System.out.println(le);
            }
        }

        if (!parser.syntaxErrors.isEmpty()) {
            System.out.println("\n==================================================");
            System.out.println("ERRORES SINT\u00c1CTICOS DETECTADOS (" + parser.syntaxErrors.size() + "):");
            System.out.println("==================================================");
            for (int i = 0; i < parser.syntaxErrors.size(); i++) {
                System.out.println("\n  Error " + (i + 1) + ": " + parser.syntaxErrors.get(i));
            }
            System.out.println("\n==================================================");
        }

        if (!parser.semanticErrors.isEmpty()) {
            for (SemanticError err : parser.semanticErrors) {
                System.out.println(err);
            }
        }

        if (hayErrores) {
            int total = parser.lexicErrors.size() + parser.syntaxErrors.size() + parser.semanticErrors.size();
            System.out.println("\n==================================================");
            System.out.println("ESTADO FINAL: Compilaci\u00f3n con " + total + " error(es). No se gener\u00f3 c\u00f3digo intermedio.");
            System.out.println("==================================================\n");
        } else {
            System.out.println("\n==================================================");
            System.out.println("ESTADO FINAL: An\u00e1lisis exitoso. Sin errores.");
            System.out.println("==================================================\n");
        }

        if (!hayErrores) {
            // --- 1. GENERAR ARCHIVO SIN OPTIMIZAR ---
            StringBuilder sbUnopt = new StringBuilder();
            sbUnopt.append("==================================================\n");
            sbUnopt.append("Codigo sin optimizar\n");
            sbUnopt.append("==================================================\n");
            sbUnopt.append(String.format("%-6s %-12s %-14s %-14s %-12s\n", "No.", "Operador", "Argumento 1", "Argumento 2", "Resultado"));
            sbUnopt.append("--------------------------------------------------\n");
            int idx1 = 0;
            for (IntermediateInstruction ins : parser.intermediateCode) {
                sbUnopt.append(String.format("%-6d %-12s %-14s %-14s %-12s\n", idx1++, ins.operator,
                    ins.arg1 != null ? ins.arg1 : "-", ins.arg2 != null ? ins.arg2 : "-", ins.result != null ? ins.result : "-"));
            }
            sbUnopt.append("--------------------------------------------------\n");
            sbUnopt.append("Total de instrucciones: ").append(parser.intermediateCode.size()).append("\n");
            String unoptFileName = baseName + "_cuadruples_unopt.txt";
            java.io.PrintWriter pwUnopt = null;
            try {
                pwUnopt = new java.io.PrintWriter(new java.io.OutputStreamWriter(new java.io.FileOutputStream(unoptFileName), "UTF-8"));
                pwUnopt.print(sbUnopt.toString());
            } catch (Exception ex) {
            } finally { if (pwUnopt != null) pwUnopt.close(); }

            // --- 2. PASAR POR EL PIPELINE DE OPTIMIZACIÓN ---
            OptimizationPipeline pipeline = new OptimizationPipeline();
            pipeline.addOptimizer(new PeepholeOptimizer());
            pipeline.addOptimizer(new CommonSubexpressionElimination());
            pipeline.addOptimizer(new CopyPropagation());
            pipeline.addOptimizer(new LoopInvariantCodeMotion());
            pipeline.addOptimizer(new DeadCodeElimination());
            List<IntermediateInstruction> finalCode = pipeline.run(parser.intermediateCode);

            // --- 3. GENERAR ARCHIVO OPTIMIZADO ---
            StringBuilder sbOpt = new StringBuilder();
            sbOpt.append("==================================================\n");
            sbOpt.append("Codigo optimizado\n");
            sbOpt.append("==================================================\n");
            sbOpt.append(String.format("%-6s %-12s %-14s %-14s %-12s\n", "No.", "Operador", "Argumento 1", "Argumento 2", "Resultado"));
            sbOpt.append("--------------------------------------------------\n");
            int idx2 = 0;
            for (IntermediateInstruction ins : finalCode) {
                sbOpt.append(String.format("%-6d %-12s %-14s %-14s %-12s\n", idx2++, ins.operator,
                    ins.arg1 != null ? ins.arg1 : "-", ins.arg2 != null ? ins.arg2 : "-", ins.result != null ? ins.result : "-"));
            }
            sbOpt.append("--------------------------------------------------\n");
            sbOpt.append("Total de instrucciones: ").append(finalCode.size()).append("\n");
            sbOpt.append("==================================================\n");
            String optFileName = baseName + "_cuadruples_opt.txt";
            java.io.PrintWriter pwOpt = null;
            try {
                pwOpt = new java.io.PrintWriter(new java.io.OutputStreamWriter(new java.io.FileOutputStream(optFileName), "UTF-8"));
                pwOpt.print(sbOpt.toString());
                System.out.println("Archivos generados exitosamente: \n- " + unoptFileName + "\n- " + optFileName);
            } catch (Exception ex) {
            } finally { if (pwOpt != null) pwOpt.close(); }

            if (!noExec) {
            // --- 4. EJECUTAR LOS CUÁDRUPLES OPTIMIZADOS EN TERMINAL ---
            System.out.println("\n==================================================");
            System.out.println("EJECUCI\u00d3N DEL PROGRAMA");
            System.out.println("==================================================");

            // Para READ interactivo: si leímos el código de stdin, necesitamos
            // abrir /dev/tty directamente para leer la entrada del usuario
            java.io.InputStream readInput = System.in;
            if (readFromStdin) {
                try {
                    readInput = new java.io.FileInputStream("/dev/tty");
                } catch (java.io.FileNotFoundException ttyEx) {
                    // Fallback: intentar System.in de todas formas (ej. en Windows)
                    readInput = System.in;
                }
            }
            java.util.Scanner sc = new java.util.Scanner(readInput);
            Map<String, Object> mem = new LinkedHashMap<String, Object>();
            Map<String, Integer> lblIdx = new HashMap<String, Integer>();
            Map<String, double[][]> matrices = new HashMap<String, double[][]>();
            Map<String, int[]> matDims = new HashMap<String, int[]>();
            Map<String, double[]> arrays = new HashMap<String, double[]>();
            Map<String, Integer> arrDims = new HashMap<String, Integer>();

            // Pre-indexar etiquetas
            for (int li = 0; li < finalCode.size(); li++) {
                IntermediateInstruction ins = finalCode.get(li);
                if (ins.operator.equals("LABEL") && ins.result != null) {
                    lblIdx.put(ins.result, li);
                }
            }

            int pc = 0;
            int maxSteps = 1000000;
            int steps = 0;
            boolean runtimeError = false;

            while (pc < finalCode.size() && steps < maxSteps && !runtimeError) {
                steps++;
                IntermediateInstruction q = finalCode.get(pc);
                String op = q.operator;

                try {
                    if (op.equals("=")) {
                        mem.put(q.result, resolveVal(q.arg1, mem));
                        pc++;
                    } else if (op.equals("+") || op.equals("-") || op.equals("*") || op.equals("/") || op.equals("%")) {
                        Object objA = resolveVal(q.arg1, mem);
                        Object objB = resolveVal(q.arg2, mem);
                        checkTypeMatch(objA, objB);

                        if (objA instanceof Integer && objB instanceof Integer) {
                            int a = (Integer) objA; int b = (Integer) objB;
                            int r = 0;
                            if (op.equals("+")) r = a + b;
                            else if (op.equals("-")) r = a - b;
                            else if (op.equals("*")) r = a * b;
                            else if (op.equals("/")) {
                                if (b == 0) throw new Exception("Divisi\u00f3n por cero entera");
                                r = a / b;
                            } else if (op.equals("%")) r = a % b;
                            mem.put(q.result, r);
                        } else {
                            double a = toNum(objA); double b = toNum(objB);
                            double r = 0;
                            if (op.equals("+")) r = a + b;
                            else if (op.equals("-")) r = a - b;
                            else if (op.equals("*")) r = a * b;
                            else if (op.equals("/")) {
                                if (b == 0) throw new Exception("Divisi\u00f3n por cero");
                                r = a / b;
                            } else if (op.equals("%")) r = a % b;
                            mem.put(q.result, r);
                        }
                        pc++;
                    } else if (op.equals("NEG")) {
                        Object objA = resolveVal(q.arg1, mem);
                        if (objA instanceof Integer) mem.put(q.result, -((Integer) objA));
                        else mem.put(q.result, -toNum(objA));
                        pc++;
                    } else if (op.equals("==")) {
                        Object a = resolveVal(q.arg1, mem); Object b = resolveVal(q.arg2, mem);
                        mem.put(q.result, eqVals(a, b) ? "TRUE" : "FALSE"); pc++;
                    } else if (op.equals("!=")) {
                        Object a = resolveVal(q.arg1, mem); Object b = resolveVal(q.arg2, mem);
                        mem.put(q.result, !eqVals(a, b) ? "TRUE" : "FALSE"); pc++;
                    } else if (op.equals("<")) {
                        double a = toNum(resolveVal(q.arg1, mem)); double b = toNum(resolveVal(q.arg2, mem));
                        mem.put(q.result, a < b ? "TRUE" : "FALSE"); pc++;
                    } else if (op.equals(">")) {
                        double a = toNum(resolveVal(q.arg1, mem)); double b = toNum(resolveVal(q.arg2, mem));
                        mem.put(q.result, a > b ? "TRUE" : "FALSE"); pc++;
                    } else if (op.equals("<=")) {
                        double a = toNum(resolveVal(q.arg1, mem)); double b = toNum(resolveVal(q.arg2, mem));
                        mem.put(q.result, a <= b ? "TRUE" : "FALSE"); pc++;
                    } else if (op.equals(">=")) {
                        double a = toNum(resolveVal(q.arg1, mem)); double b = toNum(resolveVal(q.arg2, mem));
                        mem.put(q.result, a >= b ? "TRUE" : "FALSE"); pc++;
                    } else if (op.equalsIgnoreCase("AND")) {
                        double a = toNum(resolveVal(q.arg1, mem)); double b = toNum(resolveVal(q.arg2, mem));
                        mem.put(q.result, (a != 0 && b != 0) ? "TRUE" : "FALSE"); pc++;
                    } else if (op.equalsIgnoreCase("OR")) {
                        double a = toNum(resolveVal(q.arg1, mem)); double b = toNum(resolveVal(q.arg2, mem));
                        mem.put(q.result, (a != 0 || b != 0) ? "TRUE" : "FALSE"); pc++;
                    } else if (op.equalsIgnoreCase("NOT")) {
                        double a = toNum(resolveVal(q.arg1, mem));
                        mem.put(q.result, (a == 0) ? "TRUE" : "FALSE"); pc++;
                    } else if (op.equals("WRITE")) {
                        Object val = resolveVal(q.arg1, mem);
                        System.out.println(fmtVal(val));
                        System.out.flush();
                        pc++;
                    } else if (op.equals("READ")) {
                        System.out.print(q.result + " = ? ");
                        System.out.flush();
                        String input = sc.nextLine().trim();
                        try {
                            if (input.contains(".")) mem.put(q.result, Double.parseDouble(input));
                            else mem.put(q.result, Integer.parseInt(input));
                        } catch (NumberFormatException nfe) {
                            if (input.equalsIgnoreCase("true") || input.equalsIgnoreCase("false")) {
                                mem.put(q.result, input.toUpperCase());
                            } else {
                                mem.put(q.result, "\"" + input + "\"");
                            }
                        }
                        pc++;
                    } else if (op.equals("LABEL")) {
                        pc++;
                    } else if (op.equals("GOTO")) {
                        if (lblIdx.containsKey(q.result)) pc = lblIdx.get(q.result);
                        else { System.out.println("[Error de ejecuci\u00f3n: Etiqueta no encontrada: " + q.result + "]"); runtimeError = true; }
                    } else if (op.equals("IFT")) {
                        Object condObj = resolveVal(q.arg1, mem);
                        boolean isTrue = false;
                        if (condObj instanceof String && condObj.equals("TRUE")) isTrue = true;
                        else if (condObj instanceof Number && ((Number)condObj).doubleValue() != 0) isTrue = true;

                        if (isTrue) {
                            if (lblIdx.containsKey(q.result)) pc = lblIdx.get(q.result);
                            else { System.out.println("[Error: Etiqueta no encontrada: " + q.result + "]"); runtimeError = true; }
                        } else { pc++; }
                    } else if (op.equals("NEWMAT")) {
                        String[] dims = q.arg2.split("x");
                        int d1 = Integer.parseInt(dims[0]); int d2 = Integer.parseInt(dims[1]);
                        matrices.put(q.arg1, new double[d1][d2]);
                        matDims.put(q.arg1, new int[]{d1, d2});
                        pc++;
                    } else if (op.equals("MATSET")) {
                        String[] idx = q.arg1.split(",");
                        int r = (int) toNum(resolveVal(idx[0].trim(), mem));
                        int c = (int) toNum(resolveVal(idx[1].trim(), mem));
                        double val = toNum(resolveVal(q.arg2, mem));
                        if (matrices.containsKey(q.result)) matrices.get(q.result)[r][c] = val;
                        pc++;
                    } else if (op.equals("MATGET")) {
                        String[] idx = q.arg2.split(",");
                        int r = (int) toNum(resolveVal(idx[0].trim(), mem));
                        int c = (int) toNum(resolveVal(idx[1].trim(), mem));
                        if (matrices.containsKey(q.arg1)) mem.put(q.result, matrices.get(q.arg1)[r][c]);
                        else mem.put(q.result, 0.0);
                        pc++;
                    } else if (op.equals("MATREAD")) {
                        String[] idx = q.arg1.split(",");
                        int r = (int) toNum(resolveVal(idx[0].trim(), mem));
                        int c = (int) toNum(resolveVal(idx[1].trim(), mem));
                        System.out.print(q.result + "[" + r + "][" + c + "] = ? ");
                        System.out.flush();
                        String input = sc.nextLine().trim();
                        try {
                            double val = Double.parseDouble(input);
                            if (matrices.containsKey(q.result)) matrices.get(q.result)[r][c] = val;
                        } catch (NumberFormatException nfe) {
                            System.out.println("[Error: Se esperaba un valor num\u00e9rico para la matriz]");
                        }
                        pc++;
                    } else if (op.equals("NEWARR")) {
                        int size = Integer.parseInt(q.arg2);
                        arrays.put(q.arg1, new double[size]);
                        arrDims.put(q.arg1, size);
                        pc++;
                    } else if (op.equals("ARRSET")) {
                        int idx = (int) toNum(resolveVal(q.arg1, mem));
                        double val = toNum(resolveVal(q.arg2, mem));
                        if (arrays.containsKey(q.result)) arrays.get(q.result)[idx] = val;
                        pc++;
                    } else if (op.equals("ARRGET")) {
                        int idx = (int) toNum(resolveVal(q.arg2, mem));
                        if (arrays.containsKey(q.arg1)) {
                            double v = arrays.get(q.arg1)[idx];
                            if (v == Math.floor(v)) mem.put(q.result, (int)v);
                            else mem.put(q.result, v);
                        }
                        else mem.put(q.result, 0.0);
                        pc++;
                    } else if (op.equals("ARRREAD")) {
                        int idx = (int) toNum(resolveVal(q.arg1, mem));
                        System.out.print(q.result + "[" + idx + "] = ? ");
                        System.out.flush();
                        String input = sc.nextLine().trim();
                        try {
                            double val = Double.parseDouble(input);
                            if (arrays.containsKey(q.result)) arrays.get(q.result)[idx] = val;
                        } catch (NumberFormatException nfe) {
                            System.out.println("[Error: Se esperaba un valor num\u00e9rico para el arreglo]");
                        }
                        pc++;
                    } else {
                        pc++; // operación desconocida, saltar
                    }
                } catch (Exception ex) {
                    System.out.println("[Error de ejecuci\u00f3n en instrucci\u00f3n " + pc + ": " + ex.getMessage() + "]");
                    runtimeError = true;
                }
            }

            if (steps >= maxSteps) {
                System.out.println("\n[Advertencia: Se alcanz\u00f3 el l\u00edmite de ejecuci\u00f3n (" + maxSteps + " pasos). Posible bucle infinito.]");
            }

            System.out.println("\n==================================================");
            System.out.println("Ejecuci\u00f3n finalizada.");
            System.out.println("==================================================");
            } // end if (!noExec)
        }
    }

    // --- Métodos auxiliares para el intérprete inline ---
    static Object resolveVal(String s, Map<String, Object> mem) {
        if (s == null) return 0;
        if (s.startsWith("\"") && s.endsWith("\"")) return s;
        if (s.equalsIgnoreCase("true") || s.equals("TRUE")) return "TRUE";
        if (s.equalsIgnoreCase("false") || s.equals("FALSE")) return "FALSE";
        if (mem.containsKey(s)) return mem.get(s);
        try {
            if (s.contains(".")) return Double.parseDouble(s);
            else return Integer.parseInt(s);
        } catch (NumberFormatException e) { return s; }
    }

    static void checkTypeMatch(Object a, Object b) throws Exception {
        // Se permite la coacción implícita entre REAL e INTEGER
    }

    static double toNum(Object val) throws Exception {
        if (val instanceof Number) return ((Number) val).doubleValue();
        if (val instanceof String) {
            String s = (String) val;
            if (s.startsWith("\"")) throw new Exception("No se puede realizar operacion matematica con un string: " + s);
            if (s.equals("TRUE") || s.equals("FALSE")) throw new Exception("No se puede realizar operacion matematica con un booleano: " + s);
            try { return Double.parseDouble(s); } catch (NumberFormatException e) {
                throw new Exception("Valor no numerico en operacion matematica: " + s);
            }
        }
        throw new Exception("Tipo desconocido en operacion matematica");
    }

    static boolean eqVals(Object a, Object b) {
        if (a instanceof Number && b instanceof Number) return ((Number) a).doubleValue() == ((Number) b).doubleValue();
        return String.valueOf(a).equals(String.valueOf(b));
    }

    static String fmtVal(Object val) {
        if (val instanceof Integer) return String.valueOf(val);
        if (val instanceof Double) {
            double d = (Double) val;
            if (d == Math.floor(d) && !Double.isInfinite(d)) return String.valueOf((long) d);
            return String.valueOf(d);
        }
        if (val instanceof String) {
            String s = (String) val;
            if (s.startsWith("\"") && s.endsWith("\"")) return s.substring(1, s.length() - 1);
            return s;
        }
        return String.valueOf(val);
    }

    static String getCustomTokenName(int kind) {
        switch (kind) {
            case SET:             return "SET";
            case TO:              return "TO";
            case WRITE:           return "WRITE";
            case INTEGER_LIT:     return "[ENTERO]";
            case REAL_LIT:        return "[REAL]";
            case IDENTIFIER:      return "[IDENTIFICADOR]";
            case STRING_LITERAL:  return "[CADENA]";
            case EOF:             return "[FIN DE ARCHIVO]";
            case SWITCH:          return "SWITCH";
            default:              return FelixConstants.tokenImage[kind];
        }
    }

    static String traducirExpectedTokens(ParseException e) {
        if (e.expectedTokenSequences == null) return e.getMessage();
        Set<String> expected = new HashSet<String>();
        for (int[] seq : e.expectedTokenSequences) {
            if (seq.length > 0) expected.add(getCustomTokenName(seq[0]));
        }
        return "Se esperaba uno de: " + String.join(", ", expected);
    }

  void expectSemicolon() throws ParseException {Token t = getToken(1);
    if (t.kind == SEMICOLON) {
        getNextToken();
    } else {
        if (t.kind != ERROR) {
            syntaxErrors.add("L\u00ednea " + t.beginLine + ", Columna " + t.beginColumn + ": Se esperaba ';'");
        }
        Token syncTok = getToken(1);
        while (syncTok.kind != SEMICOLON && syncTok.kind != EOF) {
            if (syncTok.kind == SET || syncTok.kind == WRITE || syncTok.kind == READ ||
                syncTok.kind == IF  || syncTok.kind == WHILE || syncTok.kind == FOR  ||
                syncTok.kind == SWITCH || syncTok.kind == NEW ||
                syncTok.kind == ELSE   || syncTok.kind == ENDIF || syncTok.kind == ENDWHILE ||
                syncTok.kind == ENDFOR || syncTok.kind == ENDSWITCH) {
                break;
            }
            getNextToken();
            syncTok = getToken(1);
        }
        if (getToken(1).kind == SEMICOLON) {
            getNextToken();
        }
    }
  }

  void expectTo() throws ParseException {Token t = getToken(1);
    if (t.kind == TO) {
        getNextToken();
    } else {
        if (t.kind != ERROR) {
            syntaxErrors.add("L\u00ednea " + t.beginLine + ", Columna " + t.beginColumn + ": Se esperaba 'TO'");
        }
        if (t.kind == ASSIGN_OP) {
            getNextToken();
        }
    }
  }

  void expectEndIf() throws ParseException {Token t = getToken(1);
    if (t.kind == ENDIF) {
        getNextToken();
    } else {
        if (t.kind != ERROR) {
            syntaxErrors.add("L\u00ednea " + t.beginLine + ", Columna " + t.beginColumn + ": Se esperaba 'ENDIF'");
        }
    }
  }

  final public void SafeStatement() throws ParseException {
    try {
      Statement();
    } catch (ParseException e) {
Token errTok = e.currentToken != null && e.currentToken.next != null
                     ? e.currentToken.next : e.currentToken;
        if (errTok == null || errTok.kind != ERROR) {
            int eLine = errTok != null ? errTok.beginLine : 0;
            int eCol  = errTok != null ? errTok.beginColumn : 0;
            syntaxErrors.add(
                "L\u00ednea " + eLine + ", Columna " + eCol + ": " +
                traducirExpectedTokens(e)
            );
        }
        // Avanzar al menos un token para evitar loops infinitos en la recuperación
        boolean consumed = false;
        Token ahead = getToken(1);
        while (ahead.kind != SEMICOLON && ahead.kind != EOF) {
            if (ahead.kind == SET   || ahead.kind == WRITE  || ahead.kind == READ ||
                ahead.kind == IF    || ahead.kind == WHILE  || ahead.kind == FOR  ||
                ahead.kind == SWITCH || ahead.kind == NEW   ||
                ahead.kind == ELSE  || ahead.kind == ENDIF  || ahead.kind == ENDWHILE ||
                ahead.kind == ENDFOR || ahead.kind == ENDSWITCH) {
                break;
            }
            getNextToken();
            consumed = true;
            ahead = getToken(1);
        }
        if (ahead.kind == SEMICOLON) {
            getNextToken(); // consumir el ';'
            consumed = true;
        }
        if (!consumed && ahead.kind != EOF) {
            getNextToken(); // Fuerza consumir el token problemático para evitar loop infinito
        }
    }
}

  void Start() throws ParseException {initTokenManager();
    while (getToken(1).kind != EOF) {
        SafeStatement();
    }
    jj_consume_token(EOF);
  }

  final public void Statement() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SET:{
      Asignacion();
      break;
      }
    case WRITE:{
      EscribirTexto();
      break;
      }
    case READ:{
      LeerVariable();
      break;
      }
    case IF:{
      Condicional();
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      if (jj_2_1(2)) {
        DeclararMatriz();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NEW:{
          DeclararArreglo();
          break;
          }
        case WHILE:{
          WhileStatement();
          break;
          }
        case FOR:{
          ForStatement();
          break;
          }
        case SWITCH:{
          SwitchStatement();
          break;
          }
        default:
          jj_la1[1] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
}

  final public void Asignacion() throws ParseException {Token id; ExprNode tree; int line, col; int errorCountBefore; boolean declaredHere = false; ExprNode rowExpr = null, colExpr = null, arrIdxExpr = null;
    jj_consume_token(SET);
    id = jj_consume_token(IDENTIFIER);
line = id.beginLine; col = id.beginColumn;
        errorCountBefore = syntaxErrors.size() + lexicErrors.size();
        if (!symbolTable.isDeclared(id.image)) {
            symbolTable.addVariable(id.image, "UNKNOWN");
            declaredHere = true;
        }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LBRACKET:{
      jj_consume_token(LBRACKET);
      Expression();
rowExpr = semanticStack.pop(); arrIdxExpr = rowExpr;
      jj_consume_token(RBRACKET);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LBRACKET:{
        jj_consume_token(LBRACKET);
        Expression();
colExpr = semanticStack.pop();
        jj_consume_token(RBRACKET);
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    expectTo();
    Expression();
    expectSemicolon();
tree = semanticStack.pop();
        ExpressionResult res = walker().walk(tree, line, col);
        int errorCountAfter = syntaxErrors.size() + lexicErrors.size();

        Symbol existing = symbolTable.lookup(id.image);

        if (rowExpr != null && colExpr != null) {
            // Asignación a matriz
            if (existing != null && !existing.type.equals("MATRIX")) {
                semanticErrors.add(new SemanticError(line, col,
                    "'" + id.image + "' no es una matriz.",
                    "Una variable de tipo MATRIX.",
                    "Use una variable declarada como matriz."));
            }
            ExpressionResult r = walker().walk(rowExpr, line, col);
            ExpressionResult c = walker().walk(colExpr, line, col);
            intermediateCode.add(new IntermediateInstruction("MATSET", r.operand + "," + c.operand, res.operand, id.image));
        } else if (arrIdxExpr != null && colExpr == null) {
            // Asignación a arreglo
            if (existing != null && !existing.type.equals("ARRAY")) {
                semanticErrors.add(new SemanticError(line, col,
                    "'" + id.image + "' no es un arreglo.",
                    "Una variable de tipo ARRAY.",
                    "Use una variable declarada como arreglo."));
            }
            ExpressionResult idx = walker().walk(arrIdxExpr, line, col);
            intermediateCode.add(new IntermediateInstruction("ARRSET", idx.operand, res.operand, id.image));
        } else {
            // Asignación simple
            String varType = res.type;
            if (errorCountAfter > errorCountBefore) {
                varType = "UNKNOWN";
            }
            if (declaredHere) {
                existing.type = varType;
            } else {
                if (!existing.type.equals(varType) && !varType.equals("UNKNOWN") && !existing.type.equals("UNKNOWN")) {
                    semanticErrors.add(new SemanticError(line, col,
                        "Asignacion incompatible: variable '" + id.image + "' es de tipo '" + existing.type +
                        "' pero se intenta asignar tipo '" + varType + "'.",
                        "Tipo " + existing.type + ".",
                        "Asigne un valor de tipo " + existing.type + " a la variable."));
                }
            }
            intermediateCode.add(new IntermediateInstruction("=", res.operand, null, id.image));
        }
}

  final public void EscribirTexto() throws ParseException {ExprNode tree; Token t;
    jj_consume_token(WRITE);
t = token;
    Expression();
tree = semanticStack.pop();
        ExpressionResult res = walker().walk(tree, t.beginLine, t.beginColumn);
        intermediateCode.add(new IntermediateInstruction("WRITE", res.operand, null, null));
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_1;
      }
      jj_consume_token(COMMA);
      Expression();
tree = semanticStack.pop();
        ExpressionResult res2 = walker().walk(tree, t.beginLine, t.beginColumn);
        intermediateCode.add(new IntermediateInstruction("WRITE", res2.operand, null, null));
    }
    expectSemicolon();
}

  final public void DeclararMatriz() throws ParseException {Token id, d1, d2;
    jj_consume_token(NEW);
    jj_consume_token(MATRIX);
    id = jj_consume_token(IDENTIFIER);
    jj_consume_token(LBRACKET);
    d1 = jj_consume_token(INTEGER_LIT);
    jj_consume_token(RBRACKET);
    jj_consume_token(LBRACKET);
    d2 = jj_consume_token(INTEGER_LIT);
    jj_consume_token(RBRACKET);
    expectSemicolon();
boolean ok = symbolTable.addMatrix(id.image,
            Integer.parseInt(d1.image), Integer.parseInt(d2.image));
        if (!ok) {
            semanticErrors.add(new SemanticError(id.beginLine, id.beginColumn,
                "Declaracion duplicada de matriz '" + id.image + "'.",
                "Un nombre de matriz no declarado previamente.",
                "Use un nombre diferente para la matriz."));
        }
        intermediateCode.add(new IntermediateInstruction("NEWMAT",
            id.image, d1.image + "x" + d2.image, null));
}

  final public void DeclararArreglo() throws ParseException {Token id, d1;
    jj_consume_token(NEW);
    jj_consume_token(ARRAY);
    id = jj_consume_token(IDENTIFIER);
    jj_consume_token(LBRACKET);
    d1 = jj_consume_token(INTEGER_LIT);
    jj_consume_token(RBRACKET);
    expectSemicolon();
boolean ok = symbolTable.addArray(id.image, Integer.parseInt(d1.image));
        if (!ok) {
            semanticErrors.add(new SemanticError(id.beginLine, id.beginColumn,
                "Declaracion duplicada de arreglo '" + id.image + "'.",
                "Un nombre de arreglo no declarado previamente.",
                "Use un nombre diferente para el arreglo."));
        }
        intermediateCode.add(new IntermediateInstruction("NEWARR", id.image, d1.image, null));
}

  final public void LeerVariable() throws ParseException {Token id; ExprNode rowExpr = null, colExpr = null, arrIdxExpr = null;
    jj_consume_token(READ);
    id = jj_consume_token(IDENTIFIER);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LBRACKET:{
      jj_consume_token(LBRACKET);
      Expression();
rowExpr = semanticStack.pop(); arrIdxExpr = rowExpr;
      jj_consume_token(RBRACKET);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LBRACKET:{
        jj_consume_token(LBRACKET);
        Expression();
colExpr = semanticStack.pop();
        jj_consume_token(RBRACKET);
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    expectSemicolon();
if (!symbolTable.isDeclared(id.image)) {
            symbolTable.addVariable(id.image, "UNKNOWN");
        }

        if (rowExpr != null && colExpr != null) {
            ExpressionResult r = walker().walk(rowExpr, id.beginLine, id.beginColumn);
            ExpressionResult c = walker().walk(colExpr, id.beginLine, id.beginColumn);
            intermediateCode.add(new IntermediateInstruction("MATREAD", r.operand + "," + c.operand, null, id.image));
        } else if (arrIdxExpr != null && colExpr == null) {
            ExpressionResult idx = walker().walk(arrIdxExpr, id.beginLine, id.beginColumn);
            intermediateCode.add(new IntermediateInstruction("ARRREAD", idx.operand, null, id.image));
        } else {
            intermediateCode.add(new IntermediateInstruction("READ", null, null, id.image));
        }
}

// ============================================================
// EXPRESSIONS
// ============================================================
  final public void Expression() throws ParseException {Token op;
    Term();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:
      case OR:
      case PLUS:
      case MINUS:
      case EQ:
      case NEQ:
      case GE:
      case LE:
      case GT:
      case LT:{
        ;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        op = jj_consume_token(PLUS);
        break;
        }
      case MINUS:{
        op = jj_consume_token(MINUS);
        break;
        }
      case EQ:{
        op = jj_consume_token(EQ);
        break;
        }
      case GT:{
        op = jj_consume_token(GT);
        break;
        }
      case GE:{
        op = jj_consume_token(GE);
        break;
        }
      case LT:{
        op = jj_consume_token(LT);
        break;
        }
      case LE:{
        op = jj_consume_token(LE);
        break;
        }
      case NEQ:{
        op = jj_consume_token(NEQ);
        break;
        }
      case AND:{
        op = jj_consume_token(AND);
        break;
        }
      case OR:{
        op = jj_consume_token(OR);
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Term();
ExprNode r = semanticStack.pop(); ExprNode l = semanticStack.pop();
        semanticStack.push(new BinaryOpNode(op.image, l, r));
    }
}

  final public void Term() throws ParseException {Token op;
    Factor();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIMES:
      case DIV:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIMES:{
        op = jj_consume_token(TIMES);
        break;
        }
      case DIV:{
        op = jj_consume_token(DIV);
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Factor();
ExprNode r = semanticStack.pop(); ExprNode l = semanticStack.pop();
        semanticStack.push(new BinaryOpNode(op.image, l, r));
    }
}

  final public void Factor() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER_LIT:{
      t = jj_consume_token(INTEGER_LIT);
semanticStack.push(new LiteralNode(t.image, "INTEGER"));
      break;
      }
    case REAL_LIT:{
      t = jj_consume_token(REAL_LIT);
semanticStack.push(new LiteralNode(t.image, "REAL"));
      break;
      }
    case STRING_LITERAL:{
      t = jj_consume_token(STRING_LITERAL);
semanticStack.push(new LiteralNode(t.image, "STRING"));
      break;
      }
    case TRUE:{
      jj_consume_token(TRUE);
semanticStack.push(new LiteralNode("true",  "BOOLEAN"));
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
semanticStack.push(new LiteralNode("false", "BOOLEAN"));
      break;
      }
    case NOT:{
      jj_consume_token(NOT);
      Factor();
ExprNode notOperand = semanticStack.pop();
        semanticStack.push(new UnaryOpNode("NOT", notOperand));
      break;
      }
    case MINUS:{
      jj_consume_token(MINUS);
      Factor();
ExprNode negOperand = semanticStack.pop();
        semanticStack.push(new UnaryOpNode("NEG", negOperand));
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      if (jj_2_2(2)) {
        t = jj_consume_token(IDENTIFIER);
        jj_consume_token(LBRACKET);
ExprNode rowExpr, colExpr = null;
        Expression(); rowExpr = semanticStack.pop();
        jj_consume_token(RBRACKET);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LBRACKET:{
          jj_consume_token(LBRACKET);
Expression(); colExpr = semanticStack.pop();
          jj_consume_token(RBRACKET);
          break;
          }
        default:
          jj_la1[11] = jj_gen;
          ;
        }
if (colExpr != null) {
            semanticStack.push(new MatrixAccessNode(t.image, rowExpr, colExpr));
        } else {
            semanticStack.push(new ArrayAccessNode(t.image, rowExpr));
        }
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFIER:{
          t = jj_consume_token(IDENTIFIER);
semanticStack.push(new VariableNode(t.image));
          break;
          }
        case LPAREN:{
          jj_consume_token(LPAREN);
          Expression();
          jj_consume_token(RPAREN);
          break;
          }
        default:
          jj_la1[13] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
}

// ============================================================
// CONTROL STRUCTURES
// ============================================================
  final public void Condicional() throws ParseException {ExprNode tree; Token t; String lTrue, lFalse, lEnd; boolean hasElse = false;
    jj_consume_token(IF);
t = token;
    Expression();
tree = semanticStack.pop();
        ExpressionResult res = walker().walk(tree, t.beginLine, t.beginColumn);
        if (!res.type.equals("BOOLEAN") && !res.type.equals("UNKNOWN")) {
            semanticErrors.add(new SemanticError(t.beginLine, t.beginColumn,
                "La condici\u00f3n del IF no es de tipo BOOLEAN (es '" + res.type + "').",
                "Expresi\u00f3n de tipo BOOLEAN.",
                "Use una expresi\u00f3n booleana como condici\u00f3n del IF."));
        }
        lTrue = newLabel(); lFalse = newLabel(); lEnd = newLabel();
        intermediateCode.add(new IntermediateInstruction("IFT",   res.operand, null, lTrue));
        intermediateCode.add(new IntermediateInstruction("GOTO",  null,        null, lFalse));
        intermediateCode.add(new IntermediateInstruction("LABEL", null,        null, lTrue));
    jj_consume_token(THEN);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SET:
      case WRITE:
      case READ:
      case IF:
      case NEW:
      case WHILE:
      case FOR:
      case SWITCH:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_4;
      }
      SafeStatement();
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
hasElse = true;
        intermediateCode.add(new IntermediateInstruction("GOTO",  null, null, lEnd));
        intermediateCode.add(new IntermediateInstruction("LABEL", null, null, lFalse));
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case SET:
        case WRITE:
        case READ:
        case IF:
        case NEW:
        case WHILE:
        case FOR:
        case SWITCH:{
          ;
          break;
          }
        default:
          jj_la1[15] = jj_gen;
          break label_5;
        }
        SafeStatement();
      }
intermediateCode.add(new IntermediateInstruction("LABEL", null, null, lEnd));
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
    expectEndIf();
if (!hasElse) {
            intermediateCode.add(new IntermediateInstruction("LABEL", null, null, lFalse));
        }
}

  final public void WhileStatement() throws ParseException {ExprNode tree; Token t; String lCond, lBody, lEnd;
    jj_consume_token(WHILE);
t = token; lCond = newLabel(); lEnd = newLabel(); lBody = newLabel();
    intermediateCode.add(new IntermediateInstruction("LABEL", null, null, lCond));
    jj_consume_token(LPAREN);
    Expression();
    jj_consume_token(RPAREN);
tree = semanticStack.pop();
        ExpressionResult res = walker().walk(tree, t.beginLine, t.beginColumn);
        if (!res.type.equals("BOOLEAN") && !res.type.equals("UNKNOWN")) {
            semanticErrors.add(new SemanticError(t.beginLine, t.beginColumn,
                "La condicion del WHILE no es de tipo BOOLEAN (es '" + res.type + "').",
                "Expresion de tipo BOOLEAN.",
                "Use una expresion booleana como condicion del WHILE."));
        }
        intermediateCode.add(new IntermediateInstruction("IFT",   res.operand, null, lBody));
        intermediateCode.add(new IntermediateInstruction("GOTO",  null,        null, lEnd));
        intermediateCode.add(new IntermediateInstruction("LABEL", null,        null, lBody));
    jj_consume_token(DO);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SET:
      case WRITE:
      case READ:
      case IF:
      case NEW:
      case WHILE:
      case FOR:
      case SWITCH:{
        ;
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        break label_6;
      }
      SafeStatement();
    }
    jj_consume_token(ENDWHILE);
intermediateCode.add(new IntermediateInstruction("GOTO",  null, null, lCond));
        intermediateCode.add(new IntermediateInstruction("LABEL", null, null, lEnd));
}

  final public void ForStatement() throws ParseException {Token id; ExprNode fromExpr, toExpr; String lCond, lBody, lEnd, condTemp, incTemp;
    jj_consume_token(FOR);
    id = jj_consume_token(IDENTIFIER);
    jj_consume_token(ASSIGN_OP);
    Expression();
fromExpr = semanticStack.pop();
    jj_consume_token(TO);
    Expression();
toExpr = semanticStack.pop();
symbolTable.addVariable(id.image, "INTEGER");
        ExpressionResult resFrom = walker().walk(fromExpr, id.beginLine, id.beginColumn);
        ExpressionResult resTo = walker().walk(toExpr, id.beginLine, id.beginColumn);
        intermediateCode.add(new IntermediateInstruction("=",     resFrom.operand,  null,      id.image));
        lCond = newLabel();
        lBody = newLabel(); lEnd = newLabel();
        condTemp = "t_for_" + id.image; incTemp = "t_inc_" + id.image;
        intermediateCode.add(new IntermediateInstruction("LABEL", null,        null,      lCond));
        intermediateCode.add(new IntermediateInstruction("<=",    id.image,    resTo.operand, condTemp));
        intermediateCode.add(new IntermediateInstruction("IFT",   condTemp,    null,      lBody));
        intermediateCode.add(new IntermediateInstruction("GOTO",  null,        null,      lEnd));
        intermediateCode.add(new IntermediateInstruction("LABEL", null,        null,      lBody));
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SET:
      case WRITE:
      case READ:
      case IF:
      case NEW:
      case WHILE:
      case FOR:
      case SWITCH:{
        ;
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        break label_7;
      }
      SafeStatement();
    }
    jj_consume_token(ENDFOR);
intermediateCode.add(new IntermediateInstruction("+",     id.image,    "1",       incTemp));
        intermediateCode.add(new IntermediateInstruction("=",     incTemp,     null,      id.image));
        intermediateCode.add(new IntermediateInstruction("GOTO",  null,        null,      lCond));
        intermediateCode.add(new IntermediateInstruction("LABEL", null,        null,      lEnd));
}

  final public void SwitchStatement() throws ParseException {Token id, num; String lEnd, lCase, skipLabel, condTemp;
    jj_consume_token(SWITCH);
    id = jj_consume_token(IDENTIFIER);
lEnd = newLabel();
        Symbol s = symbolTable.lookup(id.image);
        if (s == null) {
            semanticErrors.add(new SemanticError(id.beginLine, id.beginColumn,
                "Variable '" + id.image + "' no declarada en SWITCH.",
                "Una variable previamente declarada.",
                "Declare la variable antes del SWITCH."));
        }
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CASE:{
        ;
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        break label_8;
      }
      jj_consume_token(CASE);
      num = jj_consume_token(INTEGER_LIT);
lCase     = newLabel();
        skipLabel = newLabel();
        condTemp  = "t_sw";
        intermediateCode.add(new IntermediateInstruction("==",    id.image, num.image, condTemp));
        intermediateCode.add(new IntermediateInstruction("IFT",   condTemp, null,      lCase));
        intermediateCode.add(new IntermediateInstruction("GOTO",  null,     null,      skipLabel));
        intermediateCode.add(new IntermediateInstruction("LABEL", null,     null,      lCase));
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case SET:
        case WRITE:
        case READ:
        case IF:
        case NEW:
        case WHILE:
        case FOR:
        case SWITCH:{
          ;
          break;
          }
        default:
          jj_la1[20] = jj_gen;
          break label_9;
        }
        SafeStatement();
      }
intermediateCode.add(new IntermediateInstruction("GOTO",  null, null, lEnd));
        intermediateCode.add(new IntermediateInstruction("LABEL", null, null, skipLabel));
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DEFAULT_CASE:{
      jj_consume_token(DEFAULT_CASE);
intermediateCode.add(new IntermediateInstruction("LABEL", null, null, newLabel()));
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case SET:
        case WRITE:
        case READ:
        case IF:
        case NEW:
        case WHILE:
        case FOR:
        case SWITCH:{
          ;
          break;
          }
        default:
          jj_la1[21] = jj_gen;
          break label_10;
        }
        SafeStatement();
      }
      break;
      }
    default:
      jj_la1[22] = jj_gen;
      ;
    }
    jj_consume_token(ENDSWITCH);
intermediateCode.add(new IntermediateInstruction("LABEL", null, null, lEnd));
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_3R_DeclararMatriz_1424_5_11()
 {
    if (jj_scan_token(NEW)) return true;
    if (jj_scan_token(MATRIX)) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(LBRACKET)) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_DeclararMatriz_1424_5_11()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public FelixTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[23];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x740,0xa404000,0x0,0x0,0x0,0x0,0x0,0x60000,0x60000,0x0,0x0,0x0,0x380000,0x0,0xa404740,0xa404740,0x1000,0xa404740,0xa404740,0x10000000,0xa404740,0xa404740,0x20000000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x40,0x40,0x8000,0x40,0x40,0x3f03,0x3f03,0xc,0xc,0x40,0xb0002,0x40010,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[2];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Felix(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Felix(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new FelixTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Felix(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new FelixTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new FelixTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Felix(FelixTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(FelixTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[53];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 23; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 53; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 2; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
