<<<<<<< HEAD
/* Generated By:JavaCC: Do not edit this line. ParseException.java Version 7.0 */
/* JavaCCOptions:KEEP_LINE_COLUMN=true */
=======
/* Generated By:JavaCC: Do not edit this line. ParseException.java Version 4.1 */
/* JavaCCOptions:KEEP_LINE_COL=null */
>>>>>>> 08bf66cdcd788256f3f030b5bc603c1066dbdf5a
/**
 * This exception is thrown when parse errors are encountered.
 * You can explicitly create objects of this exception type by
 * calling the method generateParseException in the generated
 * parser.
 *
 * You can modify this class to customize your error reporting
 * mechanisms so long as you retain the public fields.
 */
public class ParseException extends Exception {

  /**
<<<<<<< HEAD
   * The version identifier for this Serializable class.
   * Increment only if the <i>serialized</i> form of the
   * class changes.
   */
  private static final long serialVersionUID = 1L;

  /**
   * The end of line string for this machine.
   */
  protected static String EOL = System.getProperty("line.separator", "\n");

  /**
   * This constructor is used by the method "generateParseException"
   * in the generated parser.  Calling this constructor generates
   * a new object of this type with the fields "currentToken",
   * "expectedTokenSequences", and "tokenImage" set.
=======
   * This constructor is used by the method "generateParseException"
   * in the generated parser.  Calling this constructor generates
   * a new object of this type with the fields "currentToken",
   * "expectedTokenSequences", and "tokenImage" set.  The boolean
   * flag "specialConstructor" is also set to true to indicate that
   * this constructor was used to create this object.
   * This constructor calls its super class with the empty string
   * to force the "toString" method of parent class "Throwable" to
   * print the error message in the form:
   *     ParseException: <result of getMessage>
>>>>>>> 08bf66cdcd788256f3f030b5bc603c1066dbdf5a
   */
  public ParseException(Token currentTokenVal,
                        int[][] expectedTokenSequencesVal,
                        String[] tokenImageVal
                       )
  {
<<<<<<< HEAD
    super(initialise(currentTokenVal, expectedTokenSequencesVal, tokenImageVal));
=======
    super("");
    specialConstructor = true;
>>>>>>> 08bf66cdcd788256f3f030b5bc603c1066dbdf5a
    currentToken = currentTokenVal;
    expectedTokenSequences = expectedTokenSequencesVal;
    tokenImage = tokenImageVal;
  }

  /**
   * The following constructors are for use by you for whatever
   * purpose you can think of.  Constructing the exception in this
   * manner makes the exception behave in the normal way - i.e., as
   * documented in the class "Throwable".  The fields "errorToken",
   * "expectedTokenSequences", and "tokenImage" do not contain
   * relevant information.  The JavaCC generated code does not use
   * these constructors.
   */

  public ParseException() {
    super();
<<<<<<< HEAD
=======
    specialConstructor = false;
>>>>>>> 08bf66cdcd788256f3f030b5bc603c1066dbdf5a
  }

  /** Constructor with message. */
  public ParseException(String message) {
    super(message);
<<<<<<< HEAD
  }

=======
    specialConstructor = false;
  }

  /**
   * This variable determines which constructor was used to create
   * this object and thereby affects the semantics of the
   * "getMessage" method (see below).
   */
  protected boolean specialConstructor;
>>>>>>> 08bf66cdcd788256f3f030b5bc603c1066dbdf5a

  /**
   * This is the last token that has been consumed successfully.  If
   * this object has been created due to a parse error, the token
<<<<<<< HEAD
   * following this token will (therefore) be the first error token.
=======
   * followng this token will (therefore) be the first error token.
>>>>>>> 08bf66cdcd788256f3f030b5bc603c1066dbdf5a
   */
  public Token currentToken;

  /**
   * Each entry in this array is an array of integers.  Each array
   * of integers represents a sequence of tokens (by their ordinal
   * values) that is expected at this point of the parse.
   */
  public int[][] expectedTokenSequences;

  /**
   * This is a reference to the "tokenImage" array of the generated
   * parser within which the parse error occurred.  This array is
   * defined in the generated ...Constants interface.
   */
  public String[] tokenImage;

  /**
<<<<<<< HEAD
   * It uses "currentToken" and "expectedTokenSequences" to generate a parse
   * error message and returns it.  If this object has been created
   * due to a parse error, and you do not catch it (it gets thrown
   * from the parser) the correct error message
   * gets displayed.
   */
  private static String initialise(Token currentToken,
                           int[][] expectedTokenSequences,
                           String[] tokenImage) {

    StringBuilder expected = new StringBuilder();
=======
   * This method has the standard behavior when this object has been
   * created using the standard constructors.  Otherwise, it uses
   * "currentToken" and "expectedTokenSequences" to generate a parse
   * error message and returns it.  If this object has been created
   * due to a parse error, and you do not catch it (it gets thrown
   * from the parser), then this method is called during the printing
   * of the final stack trace, and hence the correct error message
   * gets displayed.
   */
  public String getMessage() {
    if (!specialConstructor) {
      return super.getMessage();
    }
    StringBuffer expected = new StringBuffer();
>>>>>>> 08bf66cdcd788256f3f030b5bc603c1066dbdf5a
    int maxSize = 0;
    for (int i = 0; i < expectedTokenSequences.length; i++) {
      if (maxSize < expectedTokenSequences[i].length) {
        maxSize = expectedTokenSequences[i].length;
      }
      for (int j = 0; j < expectedTokenSequences[i].length; j++) {
        expected.append(tokenImage[expectedTokenSequences[i][j]]).append(' ');
      }
      if (expectedTokenSequences[i][expectedTokenSequences[i].length - 1] != 0) {
        expected.append("...");
      }
<<<<<<< HEAD
      expected.append(EOL).append("    ");
=======
      expected.append(eol).append("    ");
>>>>>>> 08bf66cdcd788256f3f030b5bc603c1066dbdf5a
    }
    String retval = "Encountered \"";
    Token tok = currentToken.next;
    for (int i = 0; i < maxSize; i++) {
      if (i != 0) retval += " ";
      if (tok.kind == 0) {
        retval += tokenImage[0];
        break;
      }
      retval += " " + tokenImage[tok.kind];
      retval += " \"";
      retval += add_escapes(tok.image);
      retval += " \"";
<<<<<<< HEAD
      tok = tok.next;
    }
    if (currentToken.next != null) {
      retval += "\" at line " + currentToken.next.beginLine + ", column " + currentToken.next.beginColumn;
    }
    retval += "." + EOL;
    
    
    if (expectedTokenSequences.length == 0) {
        // Nothing to add here
    } else {
	    if (expectedTokenSequences.length == 1) {
	      retval += "Was expecting:" + EOL + "    ";
	    } else {
	      retval += "Was expecting one of:" + EOL + "    ";
	    }
	    retval += expected.toString();
    }
    
    return retval;
  }


=======
      tok = tok.next; 
    }
    retval += "\" at line " + currentToken.next.beginLine + ", column " + currentToken.next.beginColumn;
    retval += "." + eol;
    if (expectedTokenSequences.length == 1) {
      retval += "Was expecting:" + eol + "    ";
    } else {
      retval += "Was expecting one of:" + eol + "    ";
    }
    retval += expected.toString();
    return retval;
  }

  /**
   * The end of line string for this machine.
   */
  protected String eol = System.getProperty("line.separator", "\n");
 
>>>>>>> 08bf66cdcd788256f3f030b5bc603c1066dbdf5a
  /**
   * Used to convert raw characters to their escaped version
   * when these raw version cannot be used as part of an ASCII
   * string literal.
   */
<<<<<<< HEAD
  static String add_escapes(String str) {
      StringBuilder retval = new StringBuilder();
=======
  protected String add_escapes(String str) {
      StringBuffer retval = new StringBuffer();
>>>>>>> 08bf66cdcd788256f3f030b5bc603c1066dbdf5a
      char ch;
      for (int i = 0; i < str.length(); i++) {
        switch (str.charAt(i))
        {
<<<<<<< HEAD
=======
           case 0 :
              continue;
>>>>>>> 08bf66cdcd788256f3f030b5bc603c1066dbdf5a
           case '\b':
              retval.append("\\b");
              continue;
           case '\t':
              retval.append("\\t");
              continue;
           case '\n':
              retval.append("\\n");
              continue;
           case '\f':
              retval.append("\\f");
              continue;
           case '\r':
              retval.append("\\r");
              continue;
           case '\"':
              retval.append("\\\"");
              continue;
           case '\'':
              retval.append("\\\'");
              continue;
           case '\\':
              retval.append("\\\\");
              continue;
           default:
              if ((ch = str.charAt(i)) < 0x20 || ch > 0x7e) {
                 String s = "0000" + Integer.toString(ch, 16);
                 retval.append("\\u" + s.substring(s.length() - 4, s.length()));
              } else {
                 retval.append(ch);
              }
              continue;
        }
      }
      return retval.toString();
   }

}
<<<<<<< HEAD
/* JavaCC - OriginalChecksum=de3ddfc6669ad4ae8d41fff7ccf6fbb7 (do not edit this line) */
=======
/* JavaCC - OriginalChecksum=be27c278eae3e59ae5dc26ba9cb2a93d (do not edit this line) */
>>>>>>> 08bf66cdcd788256f3f030b5bc603c1066dbdf5a
